(require "compiler/compiler.lisp")
(require "vm/vm.lisp")

(let ((vm '()) (program (list '+ 10 15)))
  (vm-init vm)
  (vm-load vm (comp program))
  (vm-execute vm)
  (format t "Addition de deux constantes (15+10) ~A (insn: ~A)~%" (= 25 (attr-get vm :R0)) (comp program))
)

(let ((vm '()) (program (list '- 15 10)))
  (vm-init vm)
  (vm-load vm (comp program))
  (vm-execute vm)
  (format t "Soustraction de deux constantes (15-10) ~A (insn: ~A)~%" (= 5 (attr-get vm :R0)) (comp program))
)

(let ((vm '()) (program (list '/ 10 15)))
  (vm-init vm)
  (vm-load vm (comp program))
  (vm-execute vm)
  (format t "Multiplication de deux constantes (15/10) ~A (insn: ~A)~%" (= (/ 2 3) (attr-get vm :R0)) (comp program))
)