(require "compiler/compiler.lisp")
(require "vm/vm.lisp")

(let ((vm '()) (program '(- (* 15 10) (/ 100 10))))
  (vm-init vm)
  (vm-load vm (comp program))
  (vm-execute vm)
  (format t "Une expression complexe ~A = 140: ~A~%" program (= 140 (attr-get vm :R0)))
)

(let ((vm '()) (program '(- (* 15 10) (/ 100 10))))
  (vm-init vm)
  (vm-load vm (comp program))
  (vm-execute vm)
  (format t "Une expression complexe avec variable ~A = 140: ~A~%" program (= 140 (attr-get vm :R0)))
)

(let ((vm '()) (program '(>= 3 1)))
  (vm-init vm)
  (vm-load vm (comp program))
  (vm-execute vm)
  (format t "Une comparaison ~A: ~A~%" program (= (attr-get vm :R0) 1))
)
